### ISSUE TITLE
Data is not loaded

### ISSUE THREAD

**Issue by senshaw** [chechu/serverless-dynamodb-fixtures#2]
# This is a Bug Report 

## Description
When running sls fixtures, data is not loaded, but sls deploy works. My guess is main process exits before  loading process is finished

**Comment by skrosoft** [comment]
I am in the same case, data is not loaded @chechu

**Comment by jmaleonard** [comment]
Its broken from serverless 1.31. Use serverless 1.30 if you want to use this plugin.
